bases:
  - setup

resources:
  - alertmanager-alertmanager.yaml
  - alertmanager-podDisruptionBudget.yaml
  - alertmanager-prometheusRule.yaml
  - alertmanager-secret.yaml
  - alertmanager-service.yaml
  - alertmanager-serviceAccount.yaml
  - alertmanager-serviceMonitor.yaml
  - blackbox-exporter-clusterRole.yaml
  - blackbox-exporter-clusterRoleBinding.yaml
  - blackbox-exporter-configuration.yaml
  - blackbox-exporter-deployment.yaml
  - blackbox-exporter-service.yaml
  - blackbox-exporter-serviceAccount.yaml
  - blackbox-exporter-serviceMonitor.yaml
  - grafana-dashboardDatasources.yaml
  - grafana-dashboardDefinitions.yaml
  - grafana-dashboardSources.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-serviceAccount.yaml
  - grafana-serviceMonitor.yaml
  - kube-prometheus-prometheusRule.yaml
  - kube-state-metrics-clusterRole.yaml
  - kube-state-metrics-clusterRoleBinding.yaml
  - kube-state-metrics-deployment.yaml
  - kube-state-metrics-prometheusRule.yaml
  - kube-state-metrics-service.yaml
  - kube-state-metrics-serviceAccount.yaml
  - kube-state-metrics-serviceMonitor.yaml
  - kubernetes-prometheusRule.yaml
  - kubernetes-serviceMonitorApiserver.yaml
  - kubernetes-serviceMonitorCoreDNS.yaml
  - kubernetes-serviceMonitorKubeControllerManager.yaml
  - kubernetes-serviceMonitorKubelet.yaml
  - kubernetes-serviceMonitorKubeScheduler.yaml
  - node-exporter-clusterRole.yaml
  - node-exporter-clusterRoleBinding.yaml
  - node-exporter-daemonset.yaml
  - node-exporter-prometheusRule.yaml
  - node-exporter-service.yaml
  - node-exporter-serviceAccount.yaml
  - node-exporter-serviceMonitor.yaml
  - prometheus-adapter-apiService.yaml
  - prometheus-adapter-clusterRole.yaml
  - prometheus-adapter-clusterRoleAggregatedMetricsReader.yaml
  - prometheus-adapter-clusterRoleBinding.yaml
  - prometheus-adapter-clusterRoleBindingDelegator.yaml
  - prometheus-adapter-clusterRoleServerResources.yaml
  - prometheus-adapter-configMap.yaml
  - prometheus-adapter-deployment.yaml
  - prometheus-adapter-podDisruptionBudget.yaml
  - prometheus-adapter-roleBindingAuthReader.yaml
  - prometheus-adapter-service.yaml
  - prometheus-adapter-serviceAccount.yaml
  - prometheus-adapter-serviceMonitor.yaml
  - prometheus-clusterRole.yaml
  - prometheus-clusterRoleBinding.yaml
  - prometheus-operator-prometheusRule.yaml
  - prometheus-operator-serviceMonitor.yaml
  - prometheus-podDisruptionBudget.yaml
  - prometheus-prometheus.yaml
  - prometheus-prometheusRule.yaml
  - prometheus-roleBindingConfig.yaml
  - prometheus-roleBindingSpecificNamespaces.yaml
  - prometheus-roleConfig.yaml
  - prometheus-roleSpecificNamespaces.yaml
  - prometheus-service.yaml
  - prometheus-serviceAccount.yaml
  - prometheus-serviceMonitor.yaml