[package]
name = "rust-macros"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
async-graphql = "3.0.28"
async-graphql-derive = "3.0.28"

proc-macro2 = "*"
syn = { version = "1.0.64", features = ["full", "extra-traits", "visit-mut", "visit"] }
quote = "*"