# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: simpleingressroute
#   namespace: default
# spec:
#   entryPoints:
#     - web
#   routes:
#   - match: Host(`dm.venryx.org`) && PathPrefix(`/notls`)
#     kind: Rule
#     services:
#     - name: whoami
#       port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: default
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: myresolver
  routes:
  - match: Host(`dm.venryx.org`) && PathPrefix(`/more0`)
    kind: Rule
    services:
    - name: dm-web-server
      #namespace: app
      port: 5100
  - match: Host(`dm.venryx.org`) && PathPrefix(`/more1`)
    kind: Rule
    services:
    - name: dm-web-server
      #namespace: app
      port: 5100
  # - match: Host(`dm.venryx.org`) && PathPrefix(`/more2`)
  #   kind: Rule
  #   services:
  #   - name: dm-web-server
  #     #namespace: app
  #     port: 31005

  # - match: Host(`app-server.dm.venryx.org`)
  #   kind: Rule
  #   services:
  #   - name: dm-app-server
  #     #namespace: app
  #     port: 5110