apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- Custom

resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- service-account.yaml
- daemon-set.yaml

namespace: default

commonLabels:
  app: traefik