# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: simpleingressroute
#   #namespace: traefik-attempt4
#   namespace: app
# spec:
#   entryPoints:
#     - web
#   routes:
#   - match: Host(`new.debatemap.app`)
#     kind: Rule
#     services:
#     - name: dm-web-server
#       port: 5100
#   - match: Host(`app-server.debatemap.app`)
#     kind: Rule
#     services:
#     - name: dm-app-server
#       port: 5110

# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: ingressroutetls
#   #namespace: traefik-attempt4
#   namespace: app
# spec:
#   entryPoints:
#     - websecure
#   tls:
#     certResolver: default
#   routes:
#   - match: Host(`new.debatemap.app`)
#     kind: Rule
#     services:
#     - name: dm-web-server
#       port: 5100
#   - match: Host(`app-server.debatemap.app`)
#     kind: Rule
#     services:
#     - name: dm-app-server
#       port: 5110

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`new.debatemap.app`) && PathPrefix(`/notls`)
    kind: Rule
    services:
    - name: whoami
      port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`new.debatemap.app`) && PathPrefix(`/tls`)
    kind: Rule
    services:
    - name: whoami
      port: 80
  tls:
    certResolver: default